---
- hosts: all

  tasks:
    - name: Install Apache.
      command: yum install --quiet -y httpd httpd-devel
    - name: Copy configuration file httpd.conf.
      command: >
        cp httpd.conf /etc/httpd/conf/httpd.conf
    - name: Copy configuration file httpd-vhosts.conf.
      command: >
        cp httpd-vhosts.conf /etc/httpd/conf/httpd-vhosts.conf
    - name: Start Apache and configure it to run at boot.
      command: service httpd start
    - name: Set Apache to start at boot
      command: chkconfig httpd on