# Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "geerlingguy/ubuntu2004"
    # config.vm.hostname = "nodejs.test"
    config.vm.network :private_network, ip: "192.168.60.7"
    config.vm.hostname = "drupal.test"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :virtualbox do |v|
        v.memory = 2048
    end

# Ansible Provisioner.
    config.vm.provision :ansible do |ansible|
        ansible.playbook = "provisioning/playbook.yml"
    end
end